In [1]:
import torch
import torch.nn as nn

criterion = nn.CrossEntropyLoss(ignore_index=0)
pred = torch.randn(3, 5)
target = torch.zeros(3, dtype=torch.long)
criterion(pred, target)

tensor(0.)

In [26]:
loss = torch.nn.MultiLabelSoftMarginLoss(reduction = 'none')

In [3]:
pred

tensor([[ 1.5991,  0.5208,  0.6822,  0.6874,  0.2800],
        [ 1.5029, -0.2026,  1.1794, -0.0497,  1.1592],
        [ 0.4337,  0.0155,  1.6608, -0.6669, -0.0582]])

In [27]:
tar = torch.tensor([
    [0, 1, 0, -100, 0],
    [1, 1, 1, 0, 0],
    [0, 0, 0, 1, 1]
])

In [28]:
loss(pred, tar)

tensor([14.8034,  0.6738,  1.0546])

In [29]:
pred[tar >=0]

tensor([ 1.5991,  0.5208,  0.6822,  0.2800,  1.5029, -0.2026,  1.1794, -0.0497,
         1.1592,  0.4337,  0.0155,  1.6608, -0.6669, -0.0582])

In [30]:
tar[tar >=0]

tensor([0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1])

In [31]:
loss(pred[tar >= 0].view(1, -1), tar[tar >= 0].view(1, -1))

tensor([0.9161])